steps:
#First Clone from Google Cloud Source Repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/ashok62/dotnetapp.git']
  
#Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/closetpro/demo/dotnetapp:${_VERSION}','gcp_demo/']

#Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/closetpro/demo/dotnetapp:${_VERSION}']
  
#Deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud compute ssh cloudbuild@closet-pro-vm --tunnel-through-iap --zone us-central1-a --command='sh /home/cloudbuild/deploy.sh dotnetapp v1.0'  

substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: K8scluster


    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: dotnetapp
    # _REPO_NAME: cicd-service

    # Developers ONLY change
    _VERSION: v1.1

options:
    substitution_option: 'ALLOW_LOOSE'
